### PR TITLE
RC Viewer APIs

### PR DESCRIPTION
**Pull request by hiadusum**

### CODE REVIEW

**Comment by amanbha** [comment]
@hiadusum These apis should not be merged into Services layer, its adding a ref to Newtonsoft. Whats the usecase for it?

**Comment by hiadusum** [comment]
> @hiadusum These apis should not be merged into Services layer, its adding a ref to Newtonsoft. Whats the usecase for it?

I am adding these APIs for RC Viewer that I am building. Initially, we thought about directly adding them to StatefulService.cs file. However, we are currently thinking about creating a nuget package for these changes.

**Comment by amanbha** [comment]
> > @hiadusum These apis should not be merged into Services layer, its adding a ref to Newtonsoft. Whats the usecase for it?
> 
> I am adding these APIs for RC Viewer that I am building. Initially, we thought about directly adding them to StatefulService.cs file. However, we are currently thinking about creating a nuget package for these changes.

Yes, A separate nuget seems like a good design.

**Comment by amanbha** [comment]
Closing the PR as per the discussion above.

**Pull request closed without merging**
