### PR TITLE
Update EventSource classes to check whether the EventLevel is enabled…

### PR DESCRIPTION
**Pull request by mattrowmsft**
… before paying the cost to format the event. This performance optimization is most dramatic with noise level traces.

### CODE REVIEW

**Comment by amanbha** [comment]
@mattrowmsft Could you please validate that with this change events are still traced, if yes, we can merge it.

**Comment by mattrowmsft** [comment]
Sorry I never got around to checking this.  Let me try to close on this by EOW.

**Comment by mattrowmsft** [comment]
Actually this isn't the right way to solve this.  The filtering is meant to be controlled via the Config package for the service. So while this works, I think it will break expectations on how things should work.  I think I can instead change our apps to override this configuration value to reduce amount traced.

**Comment by mattrowmsft** [comment]
Adding following to Settings.xml for SF service would set those traces to Error/Warning only. (Warning = 3)
<Settings>
  <Section Name="Tracing/ServiceFramework">
    <Parameter Name="Level" Value="3" />
  </Section>
</Settings>

**Comment by juho-hanhimaki** [comment]
> Adding following to Settings.xml for SF service would set those traces to Error/Warning only. (Warning = 3)
> 
> ```
> <Settings>
>   <Section Name="Tracing/ServiceFramework">
>     <Parameter Name="Level" Value="3" />
>   </Section>
> </Settings>
> ```

Is this documented somewhere or is it still in development? I am interested in filtering out Information level events for performance gains.

**Comment by mattrowmsft** [comment]
Glad we are open source now so I can just link to the code :-).

It is supported and working today.  I'm guessing it has been there for several releases too.  It isn't well documented but you can find all the code at following paths.

// Anything that derives from this base EventSource implementation would support this.
https://github.com/microsoft/service-fabric/blob/master/src/prod/src/managed/Microsoft.ServiceFabric.Diagnostics/Tracing/ServiceFabricEventSource.cs

// Config options set here.
https://github.com/microsoft/service-fabric/blob/master/src/prod/src/managed/Microsoft.ServiceFabric.Diagnostics/Tracing/Config/TraceConfig.cs

**Comment by juho-hanhimaki** [comment]
Great stuff. I have wondered where that bit of code is. But it is in completely different git repo :)

Regarding this PR: Purely from perf standpoint wouldn't it still make sense to filter events before formatting (in the ActorEventSource.cs and ServiceEventSource.cs)?

So without this PR the events are still formatted but then later ignored based on the configured level in the ServiceFabricEventSource.cs? Or maybe I haven't yet understood the whole picture?

**Comment by amanbha** [comment]
@juho-hanhimaki I just want to add that if you reduce the level of tracing by the service, we will not be able top provide support for the remoting calls made through the service code, users will have to rely on tracing from the service code to do any analysis when the calls fail.

**Comment by juho-hanhimaki** [comment]
@amanbha That is understandable. I don't get why it is something we should be super concerned about? We don't get support for using HttpClient or other communication method we might use between services either. Are there some major risks or is remoting fragile in some way that I don't understand?

We have operated clusters for few years now and haven't really encountered any notable problems specific to remoting. That is also why we choose to use it. It has proven to be easy to use, stable and effective for the purpose of communication between services.

In our application we have analyzed that there are some types of frequent (hot path) remoting calls where there is no value (that we can think of) for us to log each or even any one of them. Of course there are other types of calls we might want to log. That is where the current remoting stack doesn't deliver because there is no option to really configure the tracing per method or otherwise.

In the end isn't it totally up to the design, complexity and requirements of the customer application to decide the appropriate approach to tracing? The used platform/tools (SF + remoting) can have some role in that decision but I don't think it should be the main factor.

**Comment by amanbha** [comment]
@juho-hanhimaki Since Remoting is shipped as a component for writing SF services by our team,, there are some customers whose services lack proper tracing and diagnostics and file support tickets for SF Remoting related issues and our team has to provide support for those issues. So it varies from customer to customer. If you are ok with this trade off and can handle any issues by your tracing and diagnostics, then its fine.
I mentioned it explicitly for benefit of others, so if other users stumble upon this thread they are well aware of it.

**Comment by juho-hanhimaki** [comment]
Yep that makes a lot of sense.

Right now it's always a somewhat of a tradeoff whatever way one decides to go since the only way to control tracing is at the service level. If there were more granular control people could make better decisions for their specific application. Service Fabric (cluster and programming models) have quite steep learning curve and are definitely tough on beginners. But I would expect the majority of the users to be able to make smart decisions if provided the right tools and information.

**Comment by mattrowmsft** [comment]
Hey, sorry I missed explaining rest of change.

Ideally the change would still make sense as you mentioned. You avoid the formatting cost.  The reason why this won't help in practice is because SF listens to these events no matter what.  We would need to add support for configuring the trace session to allow this optimization to work.  You can see the trace session using 'logman FabricTraces -ets'.

**Comment by amanbha** [comment]
@juho-hanhimaki Yes, I agree it could have been more granular. The change suggested by @mattrowmsft above will only disable the tracing done by Services and remoting layer which use this [event source](https://github.com/microsoft/service-fabric-services-and-actors-dotnet/blob/develop/src/Microsoft.ServiceFabric.Services/Runtime/ServiceFrameworkEventSource.cs). All the tracing done by runtime for this service will still be available.

**Pull request closed without merging**
