### PR TITLE
WebServiceHost support

### PR DESCRIPTION
**Pull request by wasabii**
Added a `WcfWebCommunicationListener` which uses a `WebServiceHost` instead of a `ServiceHost`.

### CODE REVIEW

**Comment by wasabii** [comment]
This is mostly a copy of the existing `WcfCommunicationListener`, but only slightly altered to use a `WebServiceHost` instead of a `ServiceHost`.

I think it would be better if there was a `WcfCommunicationListenerBase` class, which used a generic `TServiceHost` type to set that. But I'm not going to move on that without the responsible party weighing in.

**Comment by suchiagicha** [comment]
@wasabii 
Today servicehost setter is private. You could make the func CreateServiceHost virtual protected  .
Now you can inherit the existing class and then override the CreateServiceHost function.

I hope this helps you.

**Comment by amanbha** [comment]
@wasabii Just checking if you have updates on the PR based on comments by @suchiagicha

**Comment by amanbha** [comment]
@wasabii , closing this PR because of inactivity, please feel free to reopen with updates based on the comments by @suchiagicha

**Comment by wasabii** [comment]
@suchiagicha I have implemented your suggestions. The `CreateServiceHost` and `ConfigureServiceHost` methods in the `WcfCommunicationListener` class have been made `protected virtual`, and are no longer `static`. These are then overridden by the `WcfWebCommunicationListener` class.

**Pull request closed without merging**
